### PR TITLE
Make little bit complected

### PR DESCRIPTION
**Pull request by afwn90cj93201nixr2e1re**

### CODE REVIEW

**Comment by afwn90cj93201nixr2e1re** [comment]
Added verification handler, user list.
Auto-download to dir and other stuff like that, it's work's fine for me, since january.
Also added archivating script.
изображение

**Comment by afwn90cj93201nixr2e1re** [comment]
Added verification handler, user list.
Auto-download to dir and other stuff like that, it's work's fine for me, since january.
Also added archivating script.изображение

**Comment by afwn90cj93201nixr2e1re** [comment]
It's more acceptable for 'downloader' than just url-printing.

Also we could just remove function.php - it's useless. Btw we can keep it for usage example.

**Comment by naer2** [comment]
How can i contact with you? I have some questions about this. You can contact me on Telegram with same username.

**Pull request merged**
